### ISSUE TITLE
Java API issue when running from tomcat 7

### ISSUE THREAD

**Issue by dbarral** [pabloo99/xmlsoccer#2]
Hello,

When I run from Netbeans the code, everything works well and I can retrieve data from webservice.

When the code is executed in tomcat, I get the following error : 

Caused by: org.springframework.oxm.UncategorizedMappingException: Unknown JAXB exception; nested exception is javax.xml.bind.JAXBException: Provider com.sun.xml.bind.v2.ContextFactory could not be instantiated: javax.xml.bind.JAXBException: "com.github.pabloo99.xmlsoccer.webservice" does not contain ObjectFactory.class or jaxb.index
- with linked exception:
  [javax.xml.bind.JAXBException: "com.github.pabloo99.xmlsoccer.webservice" does not contain ObjectFactory.class or jaxb.index]
  at org.springframework.oxm.jaxb.Jaxb2Marshaller.convertJaxbException(Jaxb2Marshaller.java:867)
  at org.springframework.oxm.jaxb.Jaxb2Marshaller.getJaxbContext(Jaxb2Marshaller.java:453)
  at org.springframework.oxm.jaxb.Jaxb2Marshaller.createMarshaller(Jaxb2Marshaller.java:677)
  at org.springframework.oxm.jaxb.Jaxb2Marshaller.marshal(Jaxb2Marshaller.java:640)
  at org.springframework.ws.support.MarshallingUtils.marshal(MarshallingUtils.java:81)
  at org.springframework.ws.client.core.WebServiceTemplate$2.doWithMessage(WebServiceTemplate.java:395)
  at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:573)
  at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:539)
  at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:386)
  at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:380)
  at com.github.pabloo99.xmlsoccer.client.XmlSoccerServiceImpl.getAllTeams(XmlSoccerServiceImpl.java:151)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)

Do you have any idea?

Best regards,

Dbarral

**Comment by pabloo99** [comment]
Hi,
I will try to reproduce this error on my local enviroment.

Best Regards,
pabloo99

**Comment by dbarral** [comment]
Thank you for your quick feedback. I am using Tomcat7 and Java 7, by the way.

Regards,

Daniel

**Comment by pabloo99** [comment]
I do some changes and everything is available on Maven Central Repository. Please change dependency version to 0.0.2 this is important. Please check this on your project.

**Comment by pabloo99** [comment]
Take a look on my repository: https://github.com/pabloo99/xmlsoccer_spring_boot
There is example usage xmlsoccer library with web app in Java 8 and Spring Boot. Just clone project and run Test.java class.
